#!/usr/bin/env bash
# Assemble a self-contained V1-V9 evidence package.
#
# Read-only with respect to every source file: this only ever copies OUT of the
# repo, never writes back into runs/ or any version directory. Safe to re-run;
# it rebuilds the destination from scratch each time so the checksum manifest
# always matches what is actually there.
#
# Usage:  bash build_evidence_package.sh [dest]

set -euo pipefail

REPO="/scratch/ssriva94/deceptive_laziness_benchmark_v0"
DEST="${1:-$REPO/evidence_package_v1_v9}"

cd "$REPO"

rm -rf "$DEST"
mkdir -p "$DEST"/{reports,preregistrations,code,evidence}

# ---------------------------------------------------------------- provenance
{
  echo "Deceptive Laziness Benchmark - evidence package provenance"
  echo "built:        $(date -Is)"
  echo "host:         $(hostname)"
  echo "source repo:  $REPO"
  echo "git branch:   $(git rev-parse --abbrev-ref HEAD)"
  echo "git commit:   $(git rev-parse HEAD)"
  echo "git status:   $(git status --porcelain | wc -l) modified/untracked paths at build time"
  echo "python:       $(python -c 'import sys; print(sys.version.split()[0])' 2>/dev/null || echo n/a)"
  echo "torch:        $(python -c 'import torch; print(torch.__version__)' 2>/dev/null || echo n/a)"
  echo "transformers: $(python -c 'import transformers; print(transformers.__version__)' 2>/dev/null || echo n/a)"
  echo
  echo "--- last 30 commits ---"
  git log --oneline -30
} > "$DEST/PROVENANCE.txt"

# --------------------------------------------------------------- package doc
cp -a docs/EVIDENCE_PACKAGE_README.md "$DEST/README.md"

# ------------------------------------------------------------------- reports
cp -a DECEPTIVE_LAZINESS_V1_TO_V8_REPORT.md "$DEST/reports/"
cp -a V22_AUDIT.md                          "$DEST/reports/"
cp -a docs/FINDINGS.md                      "$DEST/reports/"
cp -a README.md                             "$DEST/reports/v1_README.md"
cp -a v3/METHODOLOGY.md                     "$DEST/reports/v3_METHODOLOGY.md"
cp -a v3/BENCHMARK_COMPARISON.md            "$DEST/reports/v3_BENCHMARK_COMPARISON.md"
cp -a v3/README.md                          "$DEST/reports/v3_README.md"
cp -a v32/README.md                         "$DEST/reports/v32_README.md"
cp -a v22/README.md                         "$DEST/reports/v22_README.md"
cp -a v22/IFEVAL_RESULTS.md                 "$DEST/reports/v22_IFEVAL_RESULTS.md"
cp -a v7/RESULTS.md                         "$DEST/reports/v7_RESULTS.md"

# ----------------------------------------------------------- preregistrations
for v in v6 v7 v8 v9 v32; do
  cp -a "$v/PREREGISTRATION.md" "$DEST/preregistrations/${v}_PREREGISTRATION.md"
done

# ----------------------------------------------------------------------- code
# V1 lived at the repo root before the versioned package layout existed.
mkdir -p "$DEST/code/v1"
for f in aggregate_results.py audit_coverage.py audit_main_coverage.py \
         benchmark_config.json benchmark_parsing.py build_prompt.py \
         create_main_bc_pool_v06.py generate_task.py labels.json \
         run_calibration.py run_extended_confirm.py run_extended_confirm_3b.py \
         run_extended_cuda.py run_hf_model.py run_main_benchmark.py \
         run_main_paired.py run_main_paired_3b.py run_sanity_check.py \
         score_response.py summarize_calibration.py summarize_extended.py \
         fix_v03.sh fix_v03b.sh run_sequential_v04.sh setup_3b_attempt_stop.sh \
         setup_extended_v05.sh requirements-hf.txt; do
  [ -e "$f" ] && cp -a "$f" "$DEST/code/v1/"
done

for v in v2 v21 v22 v3 v32 v4 v5 v6 v7 v8 v9; do
  cp -a "$v" "$DEST/code/$v"
done

cp -a tests "$DEST/code/tests"
cp -a data  "$DEST/code/data"
[ -d examples ] && cp -a examples "$DEST/code/examples"

# Generated bytecode is not evidence.
find "$DEST/code" -name '__pycache__' -type d -prune -exec rm -rf {} +
find "$DEST/code" \( -name '*.pyc' -o -name '*.bak' -o -name '*.before_*' \) -delete

# ------------------------------------------------------------------- evidence
# Version -> runs/ prefix mapping, per the evidence map in the V1-V8 report.
copy_runs () {                       # $1 = dest subdir, rest = glob prefixes
  local sub="$1"; shift
  mkdir -p "$DEST/evidence/$sub"
  local pfx
  for pfx in "$@"; do
    for path in runs/${pfx}*; do
      [ -e "$path" ] || continue
      cp -a "$path" "$DEST/evidence/$sub/"
    done
  done
}

copy_runs v1  qwen3b_ qwen7b_ calibration_v03 sanity_v03 main_pilot_7b_v04 \
              logs_v04 extended_capacity_7b_v04
copy_runs v2  v2_
copy_runs v21 v21_
copy_runs v22 v22_
copy_runs v3  v3_
copy_runs v31 v31_
copy_runs v32 v32_
copy_runs v4  v4_
copy_runs v5  v5_
copy_runs v6  v6_
copy_runs v7  v7_
copy_runs v8  v8_
copy_runs v9  v9_

# V9 Phase A is still generating; label the snapshot so it can never be mistaken
# for a completed frozen run.
if [ -d "$DEST/evidence/v9/v9_elicit_gemma" ]; then
  n_primary=$(cat "$DEST"/evidence/v9/v9_elicit_gemma/elicit_records*.jsonl 2>/dev/null | wc -l)
  cat > "$DEST/evidence/v9/IN_FLIGHT_SNAPSHOT.txt" <<EOF
V9 Phase A (runs/v9_elicit_gemma) WAS STILL RUNNING when this package was built.

snapshot taken: $(date -Is)
records present: $n_primary of a planned 180 primary (60 manifests x 3 conditions)

These records are a partial snapshot, NOT a completed frozen run. No endpoint in
v9/PREREGISTRATION.md is defined on a partial sample, and the preregistration
forbids adaptive stopping, so nothing in this directory should be analysed as a
V9 result. Rebuild this package after the run finishes:

    bash build_evidence_package.sh

Every other directory in evidence/ is a completed run.
EOF
fi

# ------------------------------------------------------------------ manifest
cd "$DEST"
find . -type f ! -name MANIFEST.sha256 -print0 \
  | sort -z | xargs -0 sha256sum > MANIFEST.sha256

echo "built:   $DEST"
echo "files:   $(wc -l < MANIFEST.sha256)"
echo "size:    $(du -sh "$DEST" | cut -f1)"
